FROM apache/airflow:2.8.1

USER root

RUN apt-get update \
    && apt-get install -y --no-install-recommends python3-venv \
    && python3 -m venv /tmp/pw_venv \
    && PIP_USER=false /tmp/pw_venv/bin/pip install playwright \
    && /tmp/pw_venv/bin/playwright install-deps chromium \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && rm -rf /tmp/pw_venv

USER airflow

RUN pip install --no-cache-dir playwright beautifulsoup4

RUN playwright install chromium